[pytest]
# Опция для автоматического добавления флагов
addopts = -s -v

# Правила поиска тестовых файлов
python_files = *_tests.py test_*.py

# Правила поиска тестовых классов
python_classes = Test*

# Правила поиска тестовых функций
python_functions = test_*

markers =
    users: Маркировка для тестов, связанных с пользователями.
    regression: Маркировка для регрессионных тестов.
    files: Маркировка для тестов, связанных с файлами.
    authentication: Маркировка для тестов, связанных с аутентификацией.